#!/bin/bash

# Ending script for dev workflow
# Captures session summary and automates git workflow

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏁 Wrapping up development session..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Prompt user for summary
echo "📝 Please summarize what you achieved today:"
echo "(Type your summary and press Enter twice to finish)"
echo ""

# Read multi-line input
summary=""
while IFS= read -r line; do
    if [ -z "$line" ]; then
        if [ -n "$summary" ]; then
            break
        fi
    else
        if [ -n "$summary" ]; then
            summary="$summary"$'\n'"$line"
        else
            summary="$line"
        fi
    fi
done

echo ""
echo "✅ Summary recorded!"
echo ""

# Generate timestamp
timestamp=$(date '+%Y-%m-%d %H:%M:%S')

# Write to handover.md with timestamp
mkdir -p openspec
cat > openspec/handover.md << EOF
# Development Handover

**Timestamp:** $timestamp

## Session Summary
$summary

---
*This file is auto-generated by ending.sh. Update it with more details if needed.*
EOF

echo "📄 Handover context saved to openspec/handover.md"
echo ""

# Reminder to update tasks.md
echo "⚠️  REMINDER: Don't forget to update openspec/tasks.md if there are new tasks or changes!"
echo ""

# Git workflow
echo "🔄 Automating git workflow..."
echo ""

git add .
echo "✓ Staged all changes"

git commit -m "dev(handover): auto update"
echo "✓ Created commit"

git push origin main
echo "✓ Pushed to main branch"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ Session complete! See you next time! 👋"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
